# Generated by Django 2.1.4 on 2018-12-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0001_initial'),
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='popup',
            new_name='topup',
        ),
    ]
