# Generated by Django 2.1.4 on 2019-01-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_comments', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.CharField(max_length=10000),
        ),
    ]
