# Generated by Django 2.1.4 on 2019-01-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0001_initial'),
        ('my_comments', '0003_auto_20190102_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='log_in.user'),
            preserve_default=False,
        ),
    ]
