# Generated by Django 2.1.3 on 2018-12-17 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('AnswerText', models.CharField(max_length=500)),
                ('AnswerTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答时间')),
                ('like_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Browse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrowseTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('AnswerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Browse_AnswerID', to='administrator.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('commentText', models.CharField(max_length=500)),
                ('commentTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('AnswerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_AnswerID', to='administrator.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='关注时间')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('QuestionText', models.CharField(max_length=500)),
                ('type', models.CharField(default='', max_length=64)),
                ('follower_num', models.IntegerField(default=0)),
                ('answer_num', models.IntegerField(default=0)),
                ('askTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提问时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserName', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('passward', models.CharField(max_length=64)),
                ('status', models.CharField(default='user', max_length=64)),
                ('signupTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('country', models.CharField(default='', max_length=64)),
                ('province', models.CharField(default='', max_length=64)),
                ('city', models.CharField(default='', max_length=64)),
                ('sex', models.CharField(default='', max_length=10)),
                ('pic_height', models.IntegerField(default=100)),
                ('pic_width', models.IntegerField(default=100)),
                ('pic_url', models.ImageField(height_field='pic_height', max_length=255, upload_to='头像', width_field='pic_width')),
                ('following_num', models.IntegerField(default=0)),
                ('follower_num', models.IntegerField(default=0)),
                ('question_num', models.IntegerField(default=0)),
                ('answer_num', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phoneNum', models.CharField(default='', max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='AskerName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Question_AskerName', to='administrator.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='FollowerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follow_FollowerName', to='administrator.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follow_UserName', to='administrator.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='UserName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Comment_UserName', to='administrator.User'),
        ),
        migrations.AddField(
            model_name='browse',
            name='QuestionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Browse_QuestionID', to='administrator.Question'),
        ),
        migrations.AddField(
            model_name='browse',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Browse_UserName', to='administrator.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='AnswererName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Answer_AnswererName', to='administrator.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='QuestionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_QuestionID', to='administrator.Question'),
        ),
    ]
