# Generated by Django 2.1.4 on 2018-12-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_in', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reward_user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payuser', to='log_in.user')),
                ('reward_user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getpayuser', to='log_in.user')),
            ],
        ),
    ]
