# Generated by Django 2.1.4 on 2018-12-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=8)),
                ('user_password', models.CharField(max_length=10)),
                ('user_money', models.IntegerField(default=0)),
                ('user_image', models.CharField(default='', max_length=200)),
                ('user_nickname', models.CharField(max_length=6)),
            ],
        ),
    ]
