# Generated by Django 2.1.4 on 2019-01-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0004_auto_20190103_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_nickname',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(default='static\\img\\photo\\facebook.png', upload_to='static\\img\\photo\\%Y\\%m\\%d'),
        ),
    ]
