# Generated by Django 2.1.4 on 2019-01-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0006_auto_20190104_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='女', max_length=5),
        ),
    ]
