# Generated by Django 2.1.4 on 2019-01-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0007_auto_20190105_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
