# Generated by Django 2.1.4 on 2019-01-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0009_auto_20190106_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='私密', max_length=10),
        ),
    ]
